---
- name: Setup ECS instance
  hosts: all
  become: true
  vars_files:
    - defaults/vars.yml
    - defaults/users.yml
  handlers:
    - name: Import handlers
      ansible.builtin.import_tasks: handlers/main.yml
  roles:
    - role: common
    - role: setup
    - role: services
    - role: network
    - role: access_auth_autorization
    - role: sys_maintenance
    - role: custom
    - role: docker
      when: instance_type == "docker"
    - role: final
