---
# 3.1.1 Disable IPv6

- name: 3.1.1 - Disable IPv6
  ansible.posix.sysctl:
    name: "{{ item }}"
    value: 1
    sysctl_set: true
    state: present
    reload: true
  with_items:
    - net.ipv6.conf.all.disable_ipv6
    - net.ipv6.conf.default.disable_ipv6
  tags:
    - level-1
    - 3.1.1
    - manual
    - ignore_on_docker

- name: 3.1.1 - Disable IPv6
  ansible.builtin.command: "{{ item }}"
  with_items:
    - sysctl -w net.ipv6.conf.all.disable_ipv6=1
    - sysctl -w net.ipv6.conf.default.disable_ipv6=1
    - sysctl -w net.ipv6.route.flush=1
  tags:
    - level-1
    - 3.1.1
    - manual
    - ignore_on_docker

# 3.1.2 Ensure wireless interfaces are disabled

- name: 3.1.2 - Ensure wireless interfaces are disabled
  ansible.builtin.script: audit_3.1.2.sh
  check_mode: false
  changed_when: false
  register: audit_3_1_2
  tags:
    - level-1
    - 3.1.2
    - automated

- name: 3.1.2 - Ensure wireless interfaces are disabled
  ansible.builtin.fail:
    msg: 3.1.2 - Wireless interfaces should not be enabled
  when: audit_3_1_2.stdout != "Wireless is not enabled"
  tags:
    - level-1
    - 3.1.2
    - automated
