---

# 3.3 Network Parameters (Host and Router)
# The following network parameters are intended for use on both host only
# and router systems. A system acts as a router if it has at least two
# interfaces and is configured to perform routing functions.

# 3.3.1 Ensure source routed packets are not accepted
# 3.3.2 Ensure ICMP redirects are not accepted
# 3.3.3 Ensure secure ICMP redirects are not accepted
# 3.3.4 Ensure suspicious packets are logged
# 3.3.5 Ensure broadcast ICMP requests are ignored
# 3.3.6 Ensure bogus ICMP responses are ignored
# 3.3.7 Ensure Reverse Path Filtering is enabled
# 3.3.8 Ensure TCP SYN Cookies is enabled
# 3.3.9 Ensure IPv6 router advertisements are not accepted


# These rules are not applicable to Reepay machines as we don't use them as routers.
