---
# 3.4.1 Ensure DCCP is disabled

- name: 3.4.1 - Ensure DCCP is disabled
  ansible.builtin.lineinfile:
    # path: /etc/modprobe.d/CIS.conf
    dest: /etc/modprobe.d/CIS.conf
    line: install dccp /bin/true
    state: present
  tags:
    - level-1
    - 3.4.1
    - automated

# 3.4.2 Ensure SCTP is disabled
- name: 3.4.2 - Ensure SCTP is disabled
  ansible.builtin.lineinfile:
    # path: /etc/modprobe.d/CIS.conf
    dest: /etc/modprobe.d/CIS.conf
    line: install sctp /bin/true
    state: present
  tags:
    - level-1
    - 3.4.2
    - automated
