---
# 3.5.3 Configure iptables

# 3.5.3.1.1 Ensure iptables packages are installed
- name: 3.5.3.1.1 - Ensure iptables packages are installed
  ansible.builtin.yum:
    name: "{{ item }}"
    state: present
  with_items:
    - iptables
    - iptables-services
  tags:
    - level-1
    - 3.5.3.1.1
    - automated
    - ignore_on_docker

# 3.5.3.1.2 Ensure nftables is not installed with iptables
- name: 3.5.1.3 - Ensure nftables either not installed or masked with firewalld
  ansible.builtin.yum:
    name: nftables
    state: absent
  ignore_errors: true
  tags:
    - level-1
    - 3.5.1.3
    - automated
    - ignore_on_docker

- name: 3.5.3.1.3 - Ensure firewalld is either not installed or masked with iptables
  ansible.builtin.yum:
    name: firewalld
    state: absent
  ignore_errors: true
  when: firewalld_state == "firewalld_absent"
  tags:
    - level-1
    - 3.5.3.1.3
    - automated
    - ignore_on_docker

- name: 3.5.3.1.3 - Ensure firewalld is either not installed or masked with iptables
  ansible.builtin.systemd:
    name: firewalld
    masked: true
  ignore_errors: true
  when: firewalld_state == "firewalld_masked"
  tags:
    - level-1
    - 3.5.3.1.3
    - automated
    - ignore_on_docker

# 3.5.3.2.1 Ensure iptables loopback traffic is configured
# 3.5.3.2.2 Ensure iptables outbound and established connections are configured
# 3.5.3.2.3 Ensure iptables rules exist for all open ports
# 3.5.3.2.4 Ensure iptables default deny firewall policy
#
# These rules are not applicable to Reepay servers because we use Amazon Security Groups

# 3.5.3.2.5 Ensure iptables rules are saved
- name: 3.5.3.2.5 - Ensure iptables rules are saved
  ansible.builtin.file:
    path: /etc/sysconfig/iptables
    state: touch
    owner: root
    group: root
    mode: "0644"
  tags:
    - level-1
    - 3.5.3.2.5
    - automated
    - ignore_on_docker

# 3.5.3.2.6 Ensure iptables is enabled and running

- name: 3.5.3.2.6 - Ensure iptables is enabled and running
  ansible.builtin.service:
    name: iptables
    enabled: true
    state: started
  tags:
    - level-1
    - 3.5.3.2.6
    - automated
    - ignore_on_docker

# 3.5.3.3 Configure IPv6 ip6tables
#
# This section is not applicable to Reepay servers because we do not use IPv6
