---
# 1.6.1.1 Ensure SELinux is installed

- name: 1.6 - Install the SE Linux requirements - libselinux-python
  ansible.builtin.yum:
    name:
      - libselinux-python
      - policycoreutils-python
    state: installed

- name: 1.6.1.1 - Ensure SELinux is installed
  ansible.builtin.yum:
    name: libselinux
    state: installed

# 1.6.1.2 Ensure SELinux is not disabled in bootloader configuration

- name: 1.6.1.2 Ensure SELinux is enabled in bootloader configuration if it was previously disabled
  ansible.builtin.replace:
    dest: /etc/default/grub
    regexp: ^(GRUB_CMDLINE_LINUX_DEFAULT=.*)\"$
    replace: \1 {{ item }}=1"
  with_items:
    - selinux
    - enforcing
  notify: Reconfigure GRUB
  tags:
    - level-1
    - 1.6.1.2
    - automated
    - ignore_on_docker

- name: 1.6.1.2 - Ensure SELinux is not disabled in bootloader configuration
  ansible.builtin.script: audit_1.6.1.2.sh
  check_mode: false
  changed_when: false
  register: audit_1_6_1_2
  tags:
    - level-1
    - 1.6.1.2
    - automated
    - ignore_on_docker

- name: 1.6.1.2 - Ensure SELinux is not disabled in bootloader configuration
  ansible.builtin.fail:
    msg: "SELinux is disabled in bootloader configuration, test result is:\n{{ audit_1_6_1_2.stdout_lines }}"
  when:
    - "'FAILED' in audit_1_6_1_2.stdout"
  tags:
    - level-1
    - 1.6.1.2
    - automated
    - ignore_on_docker

# 1.6.1.3 Ensure SELinux policy is configured
# 1.6.1.4 Ensure the SELinux mode is enforcing or permissive
# 1.6.1.5 Ensure the SELinux mode is enforcing

- name: >
    1.6.1.3 Ensure SELinux policy is configured |
    1.6.1.4 Ensure the SELinux mode is enforcing or permissive |
    1.6.1.5 Ensure the SELinux mode is enforcing
  ansible.posix.selinux:
    policy: targeted
    state: enforcing
  vars:
    ansible_python_interpreter: /usr/bin/python
  tags:
    - level-1
    - 1.6.1.3
    - 1.6.1.4
    - 1.6.1.5
    - automated
    - ignore_on_docker

# 1.6.1.6 Ensure no unconfined services exist

- name: 1.6.1.6 Ensure no unconfined services exist
  ansible.builtin.script: audit_1.6.1.6.sh
  check_mode: false
  changed_when: false
  register: audit_1_6_1_6
  tags:
    - level-1
    - 1.6.1.6
    - automated

- name: 1.6.1.6 Ensure no unconfined services exist
  ansible.builtin.debug:
    msg: "*** ACTION REQUIRED *** {{ audit_1_6_1_6.stdout }}"
  when:
    - audit_1_6_1_6.stdout_lines is defined and audit_1_6_1_6.stdout_lines|length > 0
  tags:
    - level-1
    - 1.6.1.6
    - automated

# 1.6.1.7 Ensure SETroubleshoot is not installed

- name: 1.6.1.7 Ensure SETroubleshoot is not installed
  ansible.builtin.yum:
    name: setroubleshoot
    state: removed
  tags:
    - level-1
    - 1.6.1.7
    - automated

# 1.6.1.8 Ensure the MCS Translation Service (mcstrans) is not installed

- name: 1.6.1.8 Ensure the MCS Translation Service (mcstrans) is not installed
  ansible.builtin.yum:
    name: mcstrans
    state: removed
  tags:
    - level-1
    - 1.6.1.8
    - automated
