---
# 3.2 Network Parameters (Host Only)
# The following network parameters are intended for use if the system
# is to act as a host only. A system is considered host only if the system
# has a single interface, or has multiple interfaces but will not be configured as a router.

# 3.2.1 Ensure IP forwarding is disabled
- name: 3.2.1 - Ensure IP forwarding is disabled
  ansible.posix.sysctl:
    name: "{{ item }}"
    value: 0
    sysctl_set: true
    state: present
    reload: true
  with_items:
    - net.ipv4.ip_forward
    - net.ipv6.conf.all.forwarding
  tags:
    - level-1
    - 3.2.1
    - automated
    - ignore_on_docker

# 3.2.2 Ensure packet redirect sending is disabled
- name: 3.2.2 - Ensure packet redirect sending is disabled
  ansible.posix.sysctl:
    name: "{{ item }}"
    value: 0
    sysctl_set: true
    state: present
    reload: true
  with_items:
    - net.ipv4.conf.all.send_redirects
    - net.ipv4.conf.default.send_redirects
  tags:
    - level-1
    - 3.2.2
    - automated
    - ignore_on_docker
