---
# 3.5.1 Configure firewalld

# 3.5.1.1 Ensure firewalld is installed

- name: 3.5.1.1 - Ensure firewalld is installed
  ansible.builtin.yum:
    name: "{{ item }}"
    state: present
  with_items:
    - firewalld
    - iptables
    - conntrack-tools # Reqiored by firewalld
  tags:
    - level-1
    - 3.5.1.1
    - automated
    - ignore_on_docker

- name: Set SELinux permissive for firewalld
  ansible.builtin.command: semanage permissive -a firewalld_t
  tags:
    - level-1
    - 3.5.1.1
    - automated
    - ignore_on_docker

# 3.5.1.2 Ensure iptables-services not installed with firewalld

- name: 3.5.1.2 - Ensure iptables-services not installed with firewalld
  ansible.builtin.systemd:
    name: "{{ item }}"
    state: stopped
    enabled: false
  ignore_errors: true
  with_items:
    - iptables
    - ip6tables
  tags:
    - level-1
    - 3.5.1.2
    - automated
    - ignore_on_docker

- name: 3.5.1.2 - Ensure iptables-services not installed with firewalld
  ansible.builtin.yum:
    name: iptables-services
    state: absent
  tags:
    - level-1
    - 3.5.1.2
    - automated
    - ignore_on_docker

# 3.5.1.3 Ensure nftables either not installed or masked with firewalld

- name: 3.5.1.3 - Ensure nftables either not installed or masked with firewalld
  ansible.builtin.yum:
    name: nftables
    state: absent
  ignore_errors: true
  when: nftables_state == "nftables_absent"
  tags:
    - level-1
    - 3.5.1.3
    - automated
    - ignore_on_docker

- name: 3.5.1.3 - Ensure nftables either not installed or masked with firewalld
  ansible.builtin.systemd:
    name: nftables
    masked: true
  ignore_errors: true
  when: nftables_state == "nftables_masked"
  tags:
    - level-1
    - 3.5.1.3
    - automated
    - ignore_on_docker

# 3.5.1.4 Ensure firewalld service enabled and running

- name: 3.5.1.4 - Ensure firewalld service enabled and running
  ansible.builtin.systemd:
    name: firewalld
    enabled: true
    state: started
    masked: false
  tags:
    - level-1
    - 3.5.1.4
    - automated
    - ignore_on_docker

# 3.5.1.5 Ensure firewalld default zone is set

- name: 3.5.1.5 - Ensure firewalld default zone is set
  ansible.builtin.command: firewall-cmd --set-default-zone=public
  tags:
    - level-1
    - 3.5.1.5
    - automated
    - ignore_on_docker

# 3.5.1.6 Ensure network interfaces are assigned to appropriate zone
# 3.5.1.7 Ensure firewalld drops unnecessary services and ports
#
# These rules are not applicable to as FinTech Company uses Security Groups to control access to the instances
# All servers are located in AWS. All servers are restricted by AWS Security Groups.
