---
# 2.2.1 Ensure NIS Client is not installed

- name: 2.2.1 - Ensure NIS Client is not installed
  ansible.builtin.yum:
    name: ypbind
    state: absent
  ignore_errors: true
  tags:
    - level-1
    - 2.2.1
    - automated

# 2.2.2 Ensure rsh client is not installed

- name: 2.2.2 - Ensure rsh client is not installed
  ansible.builtin.yum:
    name: rsh
    state: absent
  ignore_errors: true
  tags:
    - level-1
    - 2.2.2
    - automated

# 2.2.3 Ensure talk client is not installed

- name: 2.2.3 - Ensure talk client is not installed
  ansible.builtin.yum:
    name: talk
    state: absent
  ignore_errors: true
  tags:
    - level-1
    - 2.2.3
    - automated

# 2.2.4 Ensure telnet client is not installed

- name: 2.2.4 - Ensure telnet client is not installed
  ansible.builtin.yum:
    name: telnet
    state: absent
  ignore_errors: true
  tags:
    - level-1
    - 2.2.4
    - automated

# 2.2.5 Ensure LDAP client is not installed

- name: 2.2.5 - Ensure LDAP client is not installed
  ansible.builtin.yum:
    name: openldap-clients
    state: absent
  ignore_errors: true
  tags:
    - level-1
    - 2.2.5
    - automated
