---
# 1.1.1 Ensure a separate partition for containers has been created
# Skipped

# 1.1.2 Ensure only trusted users are allowed to control Docker daemon
# Rationale: no user is needed inside docker group
- name: 1.1.2 Ensure only trusted users are allowed to control Docker daemon
  ansible.builtin.shell: >
    set -o pipefail && getent group docker | cut -d: -f4
  register: docker_group
  failed_when: docker_group.stdout != ""
  changed_when: false

# 1.1.3 Ensure auditing is configured for the Docker daemon
# 1.1.4 Ensure auditing is configured for Docker files and directories - /run/containerd
# 1.1.5 Ensure auditing is configured for Docker files and directories - /var/lib/docker
# 1.1.6 Ensure auditing is configured for Docker files and directories - /etc/docker
# 1.1.7 Ensure auditing is configured for Docker files and directories - docker.service
# 1.1.8 Ensure auditing is configured for Docker files and directories - docker.socket
# 1.1.9 Ensure auditing is configured for Docker files and directories - /etc/default/docker
# 1.1.10 Ensure auditing is configured for Docker files and directories - /etc/docker/daemon.json
# 1.1.11 Ensure auditing is configured for Docker files and directories - /etc/docker/daemon.json
# 1.1.12 Ensure auditing is configured for Docker files and directories - /etc/containerd/config.toml
# 1.1.13 Ensure auditing is configured for Docker files and directories - /etc/sysconfig/docker
# 1.1.14 Ensure auditing is configured for Docker files and directories - /usr/bin/containerd
# 1.1.15 Ensure auditing is configured for Docker files and directories - /usr/bin/containerd-shim
# 1.1.16 Ensure auditing is configured for Docker files and directories - /usr/bin/containerd-shim-runc-v1
# 1.1.17 Ensure auditing is configured for Docker files and directories - /usr/bin/containerd-shim-runc-v2
# 1.1.18 Ensure auditing is configured for Docker files and directories - /usr/bin/runc
# These rules are not applicable because we use OSSEC HIDS to monitor the system, including file and directories from the rules above

# 1.2.1 Ensure the container host has been Hardened
# This is performed by CIS related roles in this repository

# 1.2.2 Ensure that the version of Docker is up to date
# We ensure this by installing the latest version of Docker every time we run the playbook
