---
- name: |-
    3.1 Ensure that the docker.service file ownership is set to root:root
    3.2 Ensure that the docker.socket file ownership is set to root:root
  ansible.builtin.file:
    path: /usr/lib/systemd/system/docker.service
    owner: root
    group: root
    mode: "0644"

- name: |-
    3.3 Ensure that docker.socket file ownership is set to root:root
    3.4 Ensure that the docker.service file permissions are set to 644 or more restrictive
  ansible.builtin.file:
    path: /usr/lib/systemd/system/docker.socket
    owner: root
    group: root
    mode: "0644"

- name: |-
    3.5 Ensure that the /etc/docker directory ownership is set to root:root
    3.6 Ensure that the /etc/docker directory permissions are set to 755 or more restrictive
  ansible.builtin.file:
    path: /etc/docker
    owner: root
    group: root
    mode: "0755"

- name: Check  if /etc/docker/certs.d exists
  ansible.builtin.stat:
    path: /etc/docker/certs.d
  register: docker_registry_certificates

- name: |-
    3.7 Ensure that registry certificate file ownership is set to root:root
    3.8 Ensure that registry certificate file permissions are set to 444 or more restrictive
  ansible.builtin.file:
    path: /etc/docker/certs.d
    owner: root
    group: root
    mode: "0444"
    state: directory
    recurse: true
  when: docker_registry_certificates.stat.exists

# 3.9 Ensure that TLS CA certificate file ownership is set to root:root
# 3.10 Ensure that TLS CA certificate file permissions are set to 444 or more restrictive
# 3.11 Ensure that Docker server certificate file ownership is set to root:root
# 3.12 Ensure that Docker server certificate file permissions are set to 444 or more restrictive
# 3.13 Ensure that Docker server key file ownership is set to root:root
# 3.14 Ensure that Docker server key file permissions are set to 400 or more restrictive
# Ignored: there are no certificate or key files

- name: |-
    3.15 Ensure that the Docker socket file ownership is set to root:docker
    3.16 Ensure that the Docker socket file permissions are set to 660 or more restrictively
  ansible.builtin.file:
    path: /var/run/docker.sock
    owner: root
    group: root
    mode: "0660"
    state: touch

- name: |-
    3.17 Ensure that the daemon.json file ownership is set to root:root
    3.18 Ensure that daemon.json file permissions are set to 644 or more restrictive
  ansible.builtin.file:
    path: /etc/docker/daemon.json
    owner: root
    group: root
    mode: "0644"
    state: touch

# 3.19 Ensure that the /etc/default/docker file ownership is set to root:root
# 3.22 Ensure that the /etc/default/docker file permissions are set to 644 or more restrictive
# Ignored: there is no /etc/default/docker file in Amazon Linux 2

- name: |-
    3.20 Ensure that the /etc/sysconfig/docker file permissions are set to 644 or more restrictively
    3.21 Ensure that the /etc/sysconfig/docker file ownership is set to root:root
  ansible.builtin.file:
    path: /etc/sysconfig/docker
    owner: root
    group: root
    mode: "0644"
    state: touch

- name: |-
    3.23 Ensure that the Containerd socket file ownership is set to root:root
    3.24 Ensure that the Containerd socket file permissions are set to 660 or more restrictively
  ansible.builtin.file:
    path: /run/containerd/containerd.sock
    owner: root
    group: root
    mode: "0660"
    state: touch
  ignore_errors: true
