---
# 5.1 Configure time-based job schedulers

# 5.1.1 Ensure cron daemon is enabled and running
- name: 5.1.1 - Ensure cron daemon is enabled and running
  ansible.builtin.yum:
    name: cronie
    state: present
  tags:
    - level-1
    - 5.1.1
    - automated

- name: 5.1.1 - Ensure cron daemon is enabled and running
  ansible.builtin.service:
    name: crond
    state: started
    enabled: true
  tags:
    - level-1
    - 5.1.1
    - automated

# 5.1.2 Ensure permissions on /etc/crontab are configured
- name: 5.1.2 - Ensure permissions on /etc/crontab are configured
  ansible.builtin.file:
    path: /etc/crontab
    owner: root
    group: root
    mode: "0600"
  tags:
    - level-1
    - 5.1.2
    - automated

# 5.1.3 Ensure permissions on /etc/cron.hourly are configured
# 5.1.4 Ensure permissions on /etc/cron.daily are configured
# 5.1.5 Ensure permissions on /etc/cron.weekly are configured
# 5.1.6 Ensure permissions on /etc/cron.monthly are configured
# 5.1.7 Ensure permissions on /etc/cron.d are configured
- name: 5.1.3-7 - Ensure permissions on /etc/cron.* are configured
  ansible.builtin.file:
    path: /etc/cron.{{ item }}
    owner: root
    group: root
    mode: "0700"
  with_items:
    - hourly
    - daily
    - weekly
    - monthly
    - d
  tags:
    - level-1
    - 5.1.3
    - 5.1.4
    - 5.1.5
    - 5.1.6
    - 5.1.7
    - automated

# 5.1.8 Ensure cron is restricted to authorized users
# 5.1.9 Ensure at is restricted to authorized users
- name: 5.1.8-9 - Ensure cron/at is restricted to authorized users
  ansible.builtin.file:
    path: /etc/{{ item }}.deny
    state: absent
  with_items:
    - cron
    - at
  tags:
    - level-1
    - 5.1.8
    - automated

- name: 5.1.8-9 - Ensure cron/at is restricted to authorized users
  ansible.builtin.file:
    path: /etc/{{ item }}.allow
    state: touch
    owner: root
    group: root
    mode: "0600"
  with_items:
    - cron
    - at
  tags:
    - level-1
    - 5.1.8
    - automated
